version: '3'

services:

  rpc-server:
    image: python:3.7.2-alpine
    container_name: rpc-server
    ports:
      - 80:80
    volumes:
      - ./server.py:/src/server.py
    command: python /src/server.py

  rpc-client:
    image: python:3.7.2-alpine
    container_name: rpc-client
    volumes:
      - ./client.py:/src/client.py
    command : python /src/client.py
